# Generated by Django 4.2.3 on 2023-07-19 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_cart_alter_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
